#!/bin/sh
#
# @name Tiltrotor SITL with camera
#

. ${R}etc/init.d-posix/airframes/1042_tiltrotor

param set FW_R_RMAX 51

# Camera trigger interface is MAVLink
param set-default TRIG_INTERFACE 3

# Distance trigger mode enabled
param set-default TRIG_MODE 4
