#!/bin/sh
#
# @name Autonomous Systems Lab, ETH Zurich Believer
#
# @type Plane V-Tail
# @class Plane
#
# @output MAIN1 aileron right
# @output MAIN2 aileron left
# @output MAIN3 v-tail right
# @output MAIN4 v-tail left
# @output MAIN5 throttle
# @output MAIN6 wheel
# @output MAIN7 flaps right
# @output MAIN8 flaps left
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Jaeyoung Lim <jalim@ethz.ch>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default FW_AIRSPD_MIN 10
param set-default FW_AIRSPD_TRIM 20.0
param set-default FW_AIRSPD_MAX 20

param set-default FW_P_LIM_MAX 25.0
param set-default FW_P_LIM_MIN -20.0

param set-default FW_RLL_TO_YAW_FF 0.2
param set-default FW_RR_FF 0.7
param set-default FW_R_LIM 40.0
param set-default FW_THR_CRUISE 0.62
param set-default FW_T_RLL2THR 0.0
param set-default FW_YR_FF 0.4
param set-default FW_YR_P 0.2

param set-default FW_MAN_P_MAX 55
param set-default FW_MAN_R_MAX 55

param set-default FW_WR_FF 0.2
param set-default FW_WR_I 0.2
param set-default FW_WR_IMAX 0.8
param set-default FW_WR_P 1
param set-default FW_W_RMAX 0

# set disarmed value for the ESC
param set-default PWM_MAIN_DISARM 1500
param set-default PWM_MAIN_DIS5 900
param set-default PWM_MAIN_DIS6 900

# The Mini Talon does not have a wheel and
# no flaps. I leave them here because the mixer
# computes also wheel and flap controls.
set MIXER AAVVTTFF_vtail

# use PWM parameters for throttle channel
set PWM_OUT 56
